# .github/workflows/webapp.yml
name: Webapp CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Webapp CI"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
        sudo service postgresql start
        sudo systemctl enable postgresql

        # Creates DB
        sudo -u postgres psql -c "CREATE DATABASE health_check_test;"

        # Creates user
        sudo -u postgres psql -c "CREATE USER ${{ secrets.POSTGRES_USER }} WITH PASSWORD '${{ secrets.POSTGRES_PASSWORD }}';"

        # Grants access
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE health_check_test TO ${{ secrets.POSTGRES_USER }};"
        sudo -u postgres psql -d health_check_test -c "GRANT ALL ON SCHEMA public TO ${{ secrets.POSTGRES_USER }};"

        # Verify database and table exists
        echo "Checking if database exists:"
        sudo -u postgres psql -c "\l" | grep health_check_test

    - name: Install dependencies
      run: npm ci

    - name: Prepare Logging Directory
      run: |
        mkdir -p ${{ github.workspace }}/logs
        chmod 755 ${{ github.workspace }}/logs
    
    - name: Run tests
      env:
        DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/health_check_test
        NODE_ENV: test
        LOG_DIR: ${{ github.workspace }}/logs
      run: npm test

    - name: Verify Database Objects
      run: |
        echo "Checking if health_check table exists:"
        sudo -u postgres psql -d health_check_test -c "\dt health_check;"